Make KERNEL_OBJS a LOCAL_ADDITIONAL_DEPENDENCIES to prevent build errors
On a clean build linux/msm_kgsl.h is called for before kernel.mk has ran
and thus the needed header isn't available. This dependency fixes the same.

hardware/qcom/media/libc2dcolorconvert/C2DColorConverter.cpp:37:28:
fatal error: linux/msm_kgsl.h: No such file or directory
compilation terminated.

Change-Id: I55ebca12a23a7c63ec1f406206148fd78d812674